version: "3.8"

services:
  web:
    image: odoo:19.0
    container_name: odoo19_day_web
    depends_on:
      - mydb
    ports:
      - "8025:8069"
    volumes:
      - ./odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro

  mydb:
    image: postgres:16
    container_name: odoo19_day_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: myodoo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
