services:
  web:
    image: odoo:19.0
    container_name: odoo19_day_web
    depends_on:
      - mydb
    ports:
      - "8024:8069" # Us√° un puerto nuevo para evitar conflicto con 8023
    environment:
      - DB_HOST=mydb
      - DB_USER=odoo
      - DB_PASSWORD=myodoo
    volumes:
      - ./odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro

  mydb:
    image: postgres:16
    container_name: odoo19_day_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
